/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderRouteImport } from './routes/order'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EmployeeRouteRouteImport } from './routes/employee/route'
import { Route as CustumerRouteRouteImport } from './routes/custumer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as CustumerIndexRouteImport } from './routes/custumer/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as EmployeeSearchRouteImport } from './routes/employee/search'
import { Route as EmployeeReportsRouteImport } from './routes/employee/reports'
import { Route as EmployeePosRouteImport } from './routes/employee/pos'
import { Route as EmployeeInventoryRouteImport } from './routes/employee/inventory'
import { Route as ConfirmationOrderIdRouteImport } from './routes/confirmation.$orderId'
import { Route as EmployeeCreationRouteImport } from './routes/employee/creation'
import { Route as CustumerRegisterRouteImport } from './routes/custumer/register'
import { Route as CustumerLoginRouteImport } from './routes/custumer/login'
import { Route as CustumerHomeRouteImport } from './routes/custumer/home'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as EmployeeDatabaseRouteRouteImport } from './routes/employee/database/route'
import { Route as EmployeeCreateRouteRouteImport } from './routes/employee/create/route'
import { Route as EmployeeDatabaseSuppliersRouteImport } from './routes/employee/database/suppliers'
import { Route as EmployeeDatabaseRecipesRouteImport } from './routes/employee/database/recipes'
import { Route as EmployeeDatabaseMenu_itemsRouteImport } from './routes/employee/database/menu_items'
import { Route as EmployeeDatabaseIngredientsRouteImport } from './routes/employee/database/ingredients'
import { Route as EmployeeDatabaseFoodTrucksRouteImport } from './routes/employee/database/food-trucks'
import { Route as EmployeeDatabaseEmployeesRouteImport } from './routes/employee/database/employees'
import { Route as EmployeeCreateIngredientRouteImport } from './routes/employee/create/ingredient'
import { Route as EmployeeCreateEmployeeRouteImport } from './routes/employee/create/employee'

const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRouteRoute = EmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const CustumerRouteRoute = CustumerRouteRouteImport.update({
  id: '/custumer',
  path: '/custumer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const CustumerIndexRoute = CustumerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustumerRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSearchRoute = EmployeeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeReportsRoute = EmployeeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeePosRoute = EmployeePosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeInventoryRoute = EmployeeInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const ConfirmationOrderIdRoute = ConfirmationOrderIdRouteImport.update({
  id: '/confirmation/$orderId',
  path: '/confirmation/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustumerRegisterRoute = CustumerRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CustumerRouteRoute,
} as any)
const CustumerLoginRoute = CustumerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CustumerRouteRoute,
} as any)
const CustumerHomeRoute = CustumerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => CustumerRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDatabaseRouteRoute = EmployeeDatabaseRouteRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeCreateRouteRoute = EmployeeCreateRouteRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeDatabaseSuppliersRoute =
  EmployeeDatabaseSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)
const EmployeeDatabaseRecipesRoute = EmployeeDatabaseRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => EmployeeDatabaseRouteRoute,
} as any)
const EmployeeDatabaseMenu_itemsRoute =
  EmployeeDatabaseMenu_itemsRouteImport.update({
    id: '/menu_items',
    path: '/menu_items',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)
const EmployeeDatabaseIngredientsRoute =
  EmployeeDatabaseIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)
const EmployeeDatabaseFoodTrucksRoute =
  EmployeeDatabaseFoodTrucksRouteImport.update({
    id: '/food-trucks',
    path: '/food-trucks',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)
const EmployeeDatabaseEmployeesRoute =
  EmployeeDatabaseEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)
const EmployeeCreateIngredientRoute =
  EmployeeCreateIngredientRouteImport.update({
    id: '/ingredient',
    path: '/ingredient',
    getParentRoute: () => EmployeeCreateRouteRoute,
  } as any)
const EmployeeCreateEmployeeRoute = EmployeeCreateEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => EmployeeCreateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custumer': typeof CustumerRouteRouteWithChildren
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/employee/create': typeof EmployeeCreateRouteRouteWithChildren
  '/employee/database': typeof EmployeeDatabaseRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/custumer/home': typeof CustumerHomeRoute
  '/custumer/login': typeof CustumerLoginRoute
  '/custumer/register': typeof CustumerRegisterRoute
  '/employee/creation': typeof EmployeeCreationRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth/': typeof AuthIndexRoute
  '/custumer/': typeof CustumerIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/create/employee': typeof EmployeeCreateEmployeeRoute
  '/employee/create/ingredient': typeof EmployeeCreateIngredientRoute
  '/employee/database/employees': typeof EmployeeDatabaseEmployeesRoute
  '/employee/database/food-trucks': typeof EmployeeDatabaseFoodTrucksRoute
  '/employee/database/ingredients': typeof EmployeeDatabaseIngredientsRoute
  '/employee/database/menu_items': typeof EmployeeDatabaseMenu_itemsRoute
  '/employee/database/recipes': typeof EmployeeDatabaseRecipesRoute
  '/employee/database/suppliers': typeof EmployeeDatabaseSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/employee/create': typeof EmployeeCreateRouteRouteWithChildren
  '/employee/database': typeof EmployeeDatabaseRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/custumer/home': typeof CustumerHomeRoute
  '/custumer/login': typeof CustumerLoginRoute
  '/custumer/register': typeof CustumerRegisterRoute
  '/employee/creation': typeof EmployeeCreationRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth': typeof AuthIndexRoute
  '/custumer': typeof CustumerIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/employee/create/employee': typeof EmployeeCreateEmployeeRoute
  '/employee/create/ingredient': typeof EmployeeCreateIngredientRoute
  '/employee/database/employees': typeof EmployeeDatabaseEmployeesRoute
  '/employee/database/food-trucks': typeof EmployeeDatabaseFoodTrucksRoute
  '/employee/database/ingredients': typeof EmployeeDatabaseIngredientsRoute
  '/employee/database/menu_items': typeof EmployeeDatabaseMenu_itemsRoute
  '/employee/database/recipes': typeof EmployeeDatabaseRecipesRoute
  '/employee/database/suppliers': typeof EmployeeDatabaseSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custumer': typeof CustumerRouteRouteWithChildren
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/employee/create': typeof EmployeeCreateRouteRouteWithChildren
  '/employee/database': typeof EmployeeDatabaseRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/custumer/home': typeof CustumerHomeRoute
  '/custumer/login': typeof CustumerLoginRoute
  '/custumer/register': typeof CustumerRegisterRoute
  '/employee/creation': typeof EmployeeCreationRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth/': typeof AuthIndexRoute
  '/custumer/': typeof CustumerIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/create/employee': typeof EmployeeCreateEmployeeRoute
  '/employee/create/ingredient': typeof EmployeeCreateIngredientRoute
  '/employee/database/employees': typeof EmployeeDatabaseEmployeesRoute
  '/employee/database/food-trucks': typeof EmployeeDatabaseFoodTrucksRoute
  '/employee/database/ingredients': typeof EmployeeDatabaseIngredientsRoute
  '/employee/database/menu_items': typeof EmployeeDatabaseMenu_itemsRoute
  '/employee/database/recipes': typeof EmployeeDatabaseRecipesRoute
  '/employee/database/suppliers': typeof EmployeeDatabaseSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custumer'
    | '/employee'
    | '/checkout'
    | '/order'
    | '/employee/create'
    | '/employee/database'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/custumer/home'
    | '/custumer/login'
    | '/custumer/register'
    | '/employee/creation'
    | '/employee/inventory'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth/'
    | '/custumer/'
    | '/employee/'
    | '/employee/create/employee'
    | '/employee/create/ingredient'
    | '/employee/database/employees'
    | '/employee/database/food-trucks'
    | '/employee/database/ingredients'
    | '/employee/database/menu_items'
    | '/employee/database/recipes'
    | '/employee/database/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/order'
    | '/employee/create'
    | '/employee/database'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/custumer/home'
    | '/custumer/login'
    | '/custumer/register'
    | '/employee/creation'
    | '/employee/inventory'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth'
    | '/custumer'
    | '/employee'
    | '/employee/create/employee'
    | '/employee/create/ingredient'
    | '/employee/database/employees'
    | '/employee/database/food-trucks'
    | '/employee/database/ingredients'
    | '/employee/database/menu_items'
    | '/employee/database/recipes'
    | '/employee/database/suppliers'
  id:
    | '__root__'
    | '/'
    | '/custumer'
    | '/employee'
    | '/checkout'
    | '/order'
    | '/employee/create'
    | '/employee/database'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/custumer/home'
    | '/custumer/login'
    | '/custumer/register'
    | '/employee/creation'
    | '/employee/inventory'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth/'
    | '/custumer/'
    | '/employee/'
    | '/employee/create/employee'
    | '/employee/create/ingredient'
    | '/employee/database/employees'
    | '/employee/database/food-trucks'
    | '/employee/database/ingredients'
    | '/employee/database/menu_items'
    | '/employee/database/recipes'
    | '/employee/database/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustumerRouteRoute: typeof CustumerRouteRouteWithChildren
  EmployeeRouteRoute: typeof EmployeeRouteRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  OrderRoute: typeof OrderRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ConfirmationOrderIdRoute: typeof ConfirmationOrderIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custumer': {
      id: '/custumer'
      path: '/custumer'
      fullPath: '/custumer'
      preLoaderRoute: typeof CustumerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/custumer/': {
      id: '/custumer/'
      path: '/'
      fullPath: '/custumer/'
      preLoaderRoute: typeof CustumerIndexRouteImport
      parentRoute: typeof CustumerRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/search': {
      id: '/employee/search'
      path: '/search'
      fullPath: '/employee/search'
      preLoaderRoute: typeof EmployeeSearchRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/reports': {
      id: '/employee/reports'
      path: '/reports'
      fullPath: '/employee/reports'
      preLoaderRoute: typeof EmployeeReportsRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/pos': {
      id: '/employee/pos'
      path: '/pos'
      fullPath: '/employee/pos'
      preLoaderRoute: typeof EmployeePosRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/inventory': {
      id: '/employee/inventory'
      path: '/inventory'
      fullPath: '/employee/inventory'
      preLoaderRoute: typeof EmployeeInventoryRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/confirmation/$orderId': {
      id: '/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/confirmation/$orderId'
      preLoaderRoute: typeof ConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custumer/register': {
      id: '/custumer/register'
      path: '/register'
      fullPath: '/custumer/register'
      preLoaderRoute: typeof CustumerRegisterRouteImport
      parentRoute: typeof CustumerRouteRoute
    }
    '/custumer/login': {
      id: '/custumer/login'
      path: '/login'
      fullPath: '/custumer/login'
      preLoaderRoute: typeof CustumerLoginRouteImport
      parentRoute: typeof CustumerRouteRoute
    }
    '/custumer/home': {
      id: '/custumer/home'
      path: '/home'
      fullPath: '/custumer/home'
      preLoaderRoute: typeof CustumerHomeRouteImport
      parentRoute: typeof CustumerRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/database': {
      id: '/employee/database'
      path: '/database'
      fullPath: '/employee/database'
      preLoaderRoute: typeof EmployeeDatabaseRouteRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/create': {
      id: '/employee/create'
      path: '/create'
      fullPath: '/employee/create'
      preLoaderRoute: typeof EmployeeCreateRouteRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/database/suppliers': {
      id: '/employee/database/suppliers'
      path: '/suppliers'
      fullPath: '/employee/database/suppliers'
      preLoaderRoute: typeof EmployeeDatabaseSuppliersRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/recipes': {
      id: '/employee/database/recipes'
      path: '/recipes'
      fullPath: '/employee/database/recipes'
      preLoaderRoute: typeof EmployeeDatabaseRecipesRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/menu_items': {
      id: '/employee/database/menu_items'
      path: '/menu_items'
      fullPath: '/employee/database/menu_items'
      preLoaderRoute: typeof EmployeeDatabaseMenu_itemsRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/ingredients': {
      id: '/employee/database/ingredients'
      path: '/ingredients'
      fullPath: '/employee/database/ingredients'
      preLoaderRoute: typeof EmployeeDatabaseIngredientsRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/food-trucks': {
      id: '/employee/database/food-trucks'
      path: '/food-trucks'
      fullPath: '/employee/database/food-trucks'
      preLoaderRoute: typeof EmployeeDatabaseFoodTrucksRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/employees': {
      id: '/employee/database/employees'
      path: '/employees'
      fullPath: '/employee/database/employees'
      preLoaderRoute: typeof EmployeeDatabaseEmployeesRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/create/ingredient': {
      id: '/employee/create/ingredient'
      path: '/ingredient'
      fullPath: '/employee/create/ingredient'
      preLoaderRoute: typeof EmployeeCreateIngredientRouteImport
      parentRoute: typeof EmployeeCreateRouteRoute
    }
    '/employee/create/employee': {
      id: '/employee/create/employee'
      path: '/employee'
      fullPath: '/employee/create/employee'
      preLoaderRoute: typeof EmployeeCreateEmployeeRouteImport
      parentRoute: typeof EmployeeCreateRouteRoute
    }
  }
}

interface EmployeeCreateRouteRouteChildren {
  EmployeeCreateEmployeeRoute: typeof EmployeeCreateEmployeeRoute
  EmployeeCreateIngredientRoute: typeof EmployeeCreateIngredientRoute
}

const EmployeeCreateRouteRouteChildren: EmployeeCreateRouteRouteChildren = {
  EmployeeCreateEmployeeRoute: EmployeeCreateEmployeeRoute,
  EmployeeCreateIngredientRoute: EmployeeCreateIngredientRoute,
}

const EmployeeCreateRouteRouteWithChildren =
  EmployeeCreateRouteRoute._addFileChildren(EmployeeCreateRouteRouteChildren)

interface EmployeeDatabaseRouteRouteChildren {
  EmployeeDatabaseEmployeesRoute: typeof EmployeeDatabaseEmployeesRoute
  EmployeeDatabaseFoodTrucksRoute: typeof EmployeeDatabaseFoodTrucksRoute
  EmployeeDatabaseIngredientsRoute: typeof EmployeeDatabaseIngredientsRoute
  EmployeeDatabaseMenu_itemsRoute: typeof EmployeeDatabaseMenu_itemsRoute
  EmployeeDatabaseRecipesRoute: typeof EmployeeDatabaseRecipesRoute
  EmployeeDatabaseSuppliersRoute: typeof EmployeeDatabaseSuppliersRoute
}

const EmployeeDatabaseRouteRouteChildren: EmployeeDatabaseRouteRouteChildren = {
  EmployeeDatabaseEmployeesRoute: EmployeeDatabaseEmployeesRoute,
  EmployeeDatabaseFoodTrucksRoute: EmployeeDatabaseFoodTrucksRoute,
  EmployeeDatabaseIngredientsRoute: EmployeeDatabaseIngredientsRoute,
  EmployeeDatabaseMenu_itemsRoute: EmployeeDatabaseMenu_itemsRoute,
  EmployeeDatabaseRecipesRoute: EmployeeDatabaseRecipesRoute,
  EmployeeDatabaseSuppliersRoute: EmployeeDatabaseSuppliersRoute,
}

const EmployeeDatabaseRouteRouteWithChildren =
  EmployeeDatabaseRouteRoute._addFileChildren(
    EmployeeDatabaseRouteRouteChildren,
  )
interface CustumerRouteRouteChildren {
  CustumerHomeRoute: typeof CustumerHomeRoute
  CustumerLoginRoute: typeof CustumerLoginRoute
  CustumerRegisterRoute: typeof CustumerRegisterRoute
  CustumerIndexRoute: typeof CustumerIndexRoute
}

const CustumerRouteRouteChildren: CustumerRouteRouteChildren = {
  CustumerHomeRoute: CustumerHomeRoute,
  CustumerLoginRoute: CustumerLoginRoute,
  CustumerRegisterRoute: CustumerRegisterRoute,
  CustumerIndexRoute: CustumerIndexRoute,
}

const CustumerRouteRouteWithChildren = CustumerRouteRoute._addFileChildren(
  CustumerRouteRouteChildren,
)

interface EmployeeRouteRouteChildren {
  EmployeeCreateRouteRoute: typeof EmployeeCreateRouteRouteWithChildren
  EmployeeDatabaseRouteRoute: typeof EmployeeDatabaseRouteRouteWithChildren
  EmployeeInventoryRoute: typeof EmployeeInventoryRoute
  EmployeePosRoute: typeof EmployeePosRoute
  EmployeeReportsRoute: typeof EmployeeReportsRoute
  EmployeeSearchRoute: typeof EmployeeSearchRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteRouteChildren: EmployeeRouteRouteChildren = {
  EmployeeCreateRouteRoute: EmployeeCreateRouteRouteWithChildren,
  EmployeeDatabaseRouteRoute: EmployeeDatabaseRouteRouteWithChildren,
  EmployeeInventoryRoute: EmployeeInventoryRoute,
  EmployeePosRoute: EmployeePosRoute,
  EmployeeReportsRoute: EmployeeReportsRoute,
  EmployeeSearchRoute: EmployeeSearchRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteRouteWithChildren = EmployeeRouteRoute._addFileChildren(
  EmployeeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustumerRouteRoute: CustumerRouteRouteWithChildren,
  EmployeeRouteRoute: EmployeeRouteRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  OrderRoute: OrderRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ConfirmationOrderIdRoute: ConfirmationOrderIdRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
