/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderRouteImport } from './routes/order'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EmployeeRouteRouteImport } from './routes/employee/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as EmployeeSearchRouteImport } from './routes/employee/search'
import { Route as EmployeeReportsRouteImport } from './routes/employee/reports'
import { Route as EmployeePosRouteImport } from './routes/employee/pos'
import { Route as EmployeeOrdersRouteImport } from './routes/employee/orders'
import { Route as EmployeeInventoryRouteImport } from './routes/employee/inventory'
import { Route as CustomerAbautUSRouteImport } from './routes/customer/abautUS'
import { Route as ConfirmationOrderIdRouteImport } from './routes/confirmation.$orderId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as EmployeeDatabaseRouteRouteImport } from './routes/employee/database/route'
import { Route as EmployeeDatabaseUsersRouteImport } from './routes/employee/database/users'
import { Route as EmployeeDatabaseSuppliersRouteImport } from './routes/employee/database/suppliers'
import { Route as EmployeeDatabaseMenu_itemsRouteImport } from './routes/employee/database/menu_items'
import { Route as EmployeeDatabaseIngredientsRouteImport } from './routes/employee/database/ingredients'
import { Route as EmployeeDatabaseFoodTrucksRouteImport } from './routes/employee/database/food-trucks'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRouteRoute = EmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSearchRoute = EmployeeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeReportsRoute = EmployeeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeePosRoute = EmployeePosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeOrdersRoute = EmployeeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeInventoryRoute = EmployeeInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const CustomerAbautUSRoute = CustomerAbautUSRouteImport.update({
  id: '/customer/abautUS',
  path: '/customer/abautUS',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationOrderIdRoute = ConfirmationOrderIdRouteImport.update({
  id: '/confirmation/$orderId',
  path: '/confirmation/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDatabaseRouteRoute = EmployeeDatabaseRouteRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeDatabaseUsersRoute = EmployeeDatabaseUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => EmployeeDatabaseRouteRoute,
} as any)
const EmployeeDatabaseSuppliersRoute =
  EmployeeDatabaseSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)
const EmployeeDatabaseMenu_itemsRoute =
  EmployeeDatabaseMenu_itemsRouteImport.update({
    id: '/menu_items',
    path: '/menu_items',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)
const EmployeeDatabaseIngredientsRoute =
  EmployeeDatabaseIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)
const EmployeeDatabaseFoodTrucksRoute =
  EmployeeDatabaseFoodTrucksRouteImport.update({
    id: '/food-trucks',
    path: '/food-trucks',
    getParentRoute: () => EmployeeDatabaseRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/employee/database': typeof EmployeeDatabaseRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/customer/abautUS': typeof CustomerAbautUSRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth/': typeof AuthIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/database/food-trucks': typeof EmployeeDatabaseFoodTrucksRoute
  '/employee/database/ingredients': typeof EmployeeDatabaseIngredientsRoute
  '/employee/database/menu_items': typeof EmployeeDatabaseMenu_itemsRoute
  '/employee/database/suppliers': typeof EmployeeDatabaseSuppliersRoute
  '/employee/database/users': typeof EmployeeDatabaseUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/employee/database': typeof EmployeeDatabaseRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/customer/abautUS': typeof CustomerAbautUSRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth': typeof AuthIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/employee/database/food-trucks': typeof EmployeeDatabaseFoodTrucksRoute
  '/employee/database/ingredients': typeof EmployeeDatabaseIngredientsRoute
  '/employee/database/menu_items': typeof EmployeeDatabaseMenu_itemsRoute
  '/employee/database/suppliers': typeof EmployeeDatabaseSuppliersRoute
  '/employee/database/users': typeof EmployeeDatabaseUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/employee/database': typeof EmployeeDatabaseRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/customer/abautUS': typeof CustomerAbautUSRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth/': typeof AuthIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/database/food-trucks': typeof EmployeeDatabaseFoodTrucksRoute
  '/employee/database/ingredients': typeof EmployeeDatabaseIngredientsRoute
  '/employee/database/menu_items': typeof EmployeeDatabaseMenu_itemsRoute
  '/employee/database/suppliers': typeof EmployeeDatabaseSuppliersRoute
  '/employee/database/users': typeof EmployeeDatabaseUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/checkout'
    | '/order'
    | '/orders'
    | '/profile'
    | '/employee/database'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/customer/abautUS'
    | '/employee/inventory'
    | '/employee/orders'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth/'
    | '/employee/'
    | '/employee/database/food-trucks'
    | '/employee/database/ingredients'
    | '/employee/database/menu_items'
    | '/employee/database/suppliers'
    | '/employee/database/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/order'
    | '/orders'
    | '/profile'
    | '/employee/database'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/customer/abautUS'
    | '/employee/inventory'
    | '/employee/orders'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth'
    | '/employee'
    | '/employee/database/food-trucks'
    | '/employee/database/ingredients'
    | '/employee/database/menu_items'
    | '/employee/database/suppliers'
    | '/employee/database/users'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/checkout'
    | '/order'
    | '/orders'
    | '/profile'
    | '/employee/database'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/customer/abautUS'
    | '/employee/inventory'
    | '/employee/orders'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth/'
    | '/employee/'
    | '/employee/database/food-trucks'
    | '/employee/database/ingredients'
    | '/employee/database/menu_items'
    | '/employee/database/suppliers'
    | '/employee/database/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRouteRoute: typeof EmployeeRouteRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  OrderRoute: typeof OrderRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ConfirmationOrderIdRoute: typeof ConfirmationOrderIdRoute
  CustomerAbautUSRoute: typeof CustomerAbautUSRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/search': {
      id: '/employee/search'
      path: '/search'
      fullPath: '/employee/search'
      preLoaderRoute: typeof EmployeeSearchRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/reports': {
      id: '/employee/reports'
      path: '/reports'
      fullPath: '/employee/reports'
      preLoaderRoute: typeof EmployeeReportsRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/pos': {
      id: '/employee/pos'
      path: '/pos'
      fullPath: '/employee/pos'
      preLoaderRoute: typeof EmployeePosRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/orders': {
      id: '/employee/orders'
      path: '/orders'
      fullPath: '/employee/orders'
      preLoaderRoute: typeof EmployeeOrdersRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/inventory': {
      id: '/employee/inventory'
      path: '/inventory'
      fullPath: '/employee/inventory'
      preLoaderRoute: typeof EmployeeInventoryRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/customer/abautUS': {
      id: '/customer/abautUS'
      path: '/customer/abautUS'
      fullPath: '/customer/abautUS'
      preLoaderRoute: typeof CustomerAbautUSRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$orderId': {
      id: '/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/confirmation/$orderId'
      preLoaderRoute: typeof ConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/database': {
      id: '/employee/database'
      path: '/database'
      fullPath: '/employee/database'
      preLoaderRoute: typeof EmployeeDatabaseRouteRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/database/users': {
      id: '/employee/database/users'
      path: '/users'
      fullPath: '/employee/database/users'
      preLoaderRoute: typeof EmployeeDatabaseUsersRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/suppliers': {
      id: '/employee/database/suppliers'
      path: '/suppliers'
      fullPath: '/employee/database/suppliers'
      preLoaderRoute: typeof EmployeeDatabaseSuppliersRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/menu_items': {
      id: '/employee/database/menu_items'
      path: '/menu_items'
      fullPath: '/employee/database/menu_items'
      preLoaderRoute: typeof EmployeeDatabaseMenu_itemsRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/ingredients': {
      id: '/employee/database/ingredients'
      path: '/ingredients'
      fullPath: '/employee/database/ingredients'
      preLoaderRoute: typeof EmployeeDatabaseIngredientsRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
    '/employee/database/food-trucks': {
      id: '/employee/database/food-trucks'
      path: '/food-trucks'
      fullPath: '/employee/database/food-trucks'
      preLoaderRoute: typeof EmployeeDatabaseFoodTrucksRouteImport
      parentRoute: typeof EmployeeDatabaseRouteRoute
    }
  }
}

interface EmployeeDatabaseRouteRouteChildren {
  EmployeeDatabaseFoodTrucksRoute: typeof EmployeeDatabaseFoodTrucksRoute
  EmployeeDatabaseIngredientsRoute: typeof EmployeeDatabaseIngredientsRoute
  EmployeeDatabaseMenu_itemsRoute: typeof EmployeeDatabaseMenu_itemsRoute
  EmployeeDatabaseSuppliersRoute: typeof EmployeeDatabaseSuppliersRoute
  EmployeeDatabaseUsersRoute: typeof EmployeeDatabaseUsersRoute
}

const EmployeeDatabaseRouteRouteChildren: EmployeeDatabaseRouteRouteChildren = {
  EmployeeDatabaseFoodTrucksRoute: EmployeeDatabaseFoodTrucksRoute,
  EmployeeDatabaseIngredientsRoute: EmployeeDatabaseIngredientsRoute,
  EmployeeDatabaseMenu_itemsRoute: EmployeeDatabaseMenu_itemsRoute,
  EmployeeDatabaseSuppliersRoute: EmployeeDatabaseSuppliersRoute,
  EmployeeDatabaseUsersRoute: EmployeeDatabaseUsersRoute,
}

const EmployeeDatabaseRouteRouteWithChildren =
  EmployeeDatabaseRouteRoute._addFileChildren(
    EmployeeDatabaseRouteRouteChildren,
  )

interface EmployeeRouteRouteChildren {
  EmployeeDatabaseRouteRoute: typeof EmployeeDatabaseRouteRouteWithChildren
  EmployeeInventoryRoute: typeof EmployeeInventoryRoute
  EmployeeOrdersRoute: typeof EmployeeOrdersRoute
  EmployeePosRoute: typeof EmployeePosRoute
  EmployeeReportsRoute: typeof EmployeeReportsRoute
  EmployeeSearchRoute: typeof EmployeeSearchRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteRouteChildren: EmployeeRouteRouteChildren = {
  EmployeeDatabaseRouteRoute: EmployeeDatabaseRouteRouteWithChildren,
  EmployeeInventoryRoute: EmployeeInventoryRoute,
  EmployeeOrdersRoute: EmployeeOrdersRoute,
  EmployeePosRoute: EmployeePosRoute,
  EmployeeReportsRoute: EmployeeReportsRoute,
  EmployeeSearchRoute: EmployeeSearchRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteRouteWithChildren = EmployeeRouteRoute._addFileChildren(
  EmployeeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRouteRoute: EmployeeRouteRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  OrderRoute: OrderRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ConfirmationOrderIdRoute: ConfirmationOrderIdRoute,
  CustomerAbautUSRoute: CustomerAbautUSRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
