/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderRouteImport } from './routes/order'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EmployeeRouteRouteImport } from './routes/employee/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as EmployeeSearchRouteImport } from './routes/employee/search'
import { Route as EmployeeReportsRouteImport } from './routes/employee/reports'
import { Route as EmployeePosRouteImport } from './routes/employee/pos'
import { Route as EmployeeInventoryRouteImport } from './routes/employee/inventory'
import { Route as ConfirmationOrderIdRouteImport } from './routes/confirmation.$orderId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as EmployeeCreateRouteRouteImport } from './routes/employee/create/route'
import { Route as EmployeeCreateIngredientRouteImport } from './routes/employee/create/ingredient'
import { Route as EmployeeCreateEmployeeRouteImport } from './routes/employee/create/employee'

const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRouteRoute = EmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSearchRoute = EmployeeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeReportsRoute = EmployeeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeePosRoute = EmployeePosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeInventoryRoute = EmployeeInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const ConfirmationOrderIdRoute = ConfirmationOrderIdRouteImport.update({
  id: '/confirmation/$orderId',
  path: '/confirmation/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeCreateRouteRoute = EmployeeCreateRouteRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeCreateIngredientRoute =
  EmployeeCreateIngredientRouteImport.update({
    id: '/ingredient',
    path: '/ingredient',
    getParentRoute: () => EmployeeCreateRouteRoute,
  } as any)
const EmployeeCreateEmployeeRoute = EmployeeCreateEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => EmployeeCreateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/employee/create': typeof EmployeeCreateRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth/': typeof AuthIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/create/employee': typeof EmployeeCreateEmployeeRoute
  '/employee/create/ingredient': typeof EmployeeCreateIngredientRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/employee/create': typeof EmployeeCreateRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth': typeof AuthIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/employee/create/employee': typeof EmployeeCreateEmployeeRoute
  '/employee/create/ingredient': typeof EmployeeCreateIngredientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/order': typeof OrderRoute
  '/employee/create': typeof EmployeeCreateRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/pos': typeof EmployeePosRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/search': typeof EmployeeSearchRoute
  '/auth/': typeof AuthIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/create/employee': typeof EmployeeCreateEmployeeRoute
  '/employee/create/ingredient': typeof EmployeeCreateIngredientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/checkout'
    | '/order'
    | '/employee/create'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/employee/inventory'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth/'
    | '/employee/'
    | '/employee/create/employee'
    | '/employee/create/ingredient'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/order'
    | '/employee/create'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/employee/inventory'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth'
    | '/employee'
    | '/employee/create/employee'
    | '/employee/create/ingredient'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/checkout'
    | '/order'
    | '/employee/create'
    | '/auth/login'
    | '/auth/signup'
    | '/confirmation/$orderId'
    | '/employee/inventory'
    | '/employee/pos'
    | '/employee/reports'
    | '/employee/search'
    | '/auth/'
    | '/employee/'
    | '/employee/create/employee'
    | '/employee/create/ingredient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRouteRoute: typeof EmployeeRouteRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  OrderRoute: typeof OrderRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ConfirmationOrderIdRoute: typeof ConfirmationOrderIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/search': {
      id: '/employee/search'
      path: '/search'
      fullPath: '/employee/search'
      preLoaderRoute: typeof EmployeeSearchRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/reports': {
      id: '/employee/reports'
      path: '/reports'
      fullPath: '/employee/reports'
      preLoaderRoute: typeof EmployeeReportsRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/pos': {
      id: '/employee/pos'
      path: '/pos'
      fullPath: '/employee/pos'
      preLoaderRoute: typeof EmployeePosRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/inventory': {
      id: '/employee/inventory'
      path: '/inventory'
      fullPath: '/employee/inventory'
      preLoaderRoute: typeof EmployeeInventoryRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/confirmation/$orderId': {
      id: '/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/confirmation/$orderId'
      preLoaderRoute: typeof ConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/create': {
      id: '/employee/create'
      path: '/create'
      fullPath: '/employee/create'
      preLoaderRoute: typeof EmployeeCreateRouteRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/create/ingredient': {
      id: '/employee/create/ingredient'
      path: '/ingredient'
      fullPath: '/employee/create/ingredient'
      preLoaderRoute: typeof EmployeeCreateIngredientRouteImport
      parentRoute: typeof EmployeeCreateRouteRoute
    }
    '/employee/create/employee': {
      id: '/employee/create/employee'
      path: '/employee'
      fullPath: '/employee/create/employee'
      preLoaderRoute: typeof EmployeeCreateEmployeeRouteImport
      parentRoute: typeof EmployeeCreateRouteRoute
    }
  }
}

interface EmployeeCreateRouteRouteChildren {
  EmployeeCreateEmployeeRoute: typeof EmployeeCreateEmployeeRoute
  EmployeeCreateIngredientRoute: typeof EmployeeCreateIngredientRoute
}

const EmployeeCreateRouteRouteChildren: EmployeeCreateRouteRouteChildren = {
  EmployeeCreateEmployeeRoute: EmployeeCreateEmployeeRoute,
  EmployeeCreateIngredientRoute: EmployeeCreateIngredientRoute,
}

const EmployeeCreateRouteRouteWithChildren =
  EmployeeCreateRouteRoute._addFileChildren(EmployeeCreateRouteRouteChildren)

interface EmployeeRouteRouteChildren {
  EmployeeCreateRouteRoute: typeof EmployeeCreateRouteRouteWithChildren
  EmployeeInventoryRoute: typeof EmployeeInventoryRoute
  EmployeePosRoute: typeof EmployeePosRoute
  EmployeeReportsRoute: typeof EmployeeReportsRoute
  EmployeeSearchRoute: typeof EmployeeSearchRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteRouteChildren: EmployeeRouteRouteChildren = {
  EmployeeCreateRouteRoute: EmployeeCreateRouteRouteWithChildren,
  EmployeeInventoryRoute: EmployeeInventoryRoute,
  EmployeePosRoute: EmployeePosRoute,
  EmployeeReportsRoute: EmployeeReportsRoute,
  EmployeeSearchRoute: EmployeeSearchRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteRouteWithChildren = EmployeeRouteRoute._addFileChildren(
  EmployeeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRouteRoute: EmployeeRouteRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  OrderRoute: OrderRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ConfirmationOrderIdRoute: ConfirmationOrderIdRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
