name: Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (root)
        run: npm install

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build root
        run: npm run build

    #   Building backend just starts the server
    #   TODO: Figure out how to build turborepo
    #   - name: Build backend (if applicable)
    #     run: |
    #       if [ -f package.json ] && grep -q 'build' package.json; then npm run build; else echo "No build script"; fi
    #     working-directory: backend
