# name: Build and Deploy
# on:
#   push:
#     branches: ["main"] # Trigger on pushes to main branch
# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: "papatenko/point-of-sales"

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - uses: actions/checkout@v3
#       - name: Login to registry
#         uses: docker/login-action@v2
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Build and push image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: Dockerfile
#           platforms: linux/amd64
#           push: true
#           tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
#       - name: Deploy to Coolify
#         run: |
#           curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
